Add mounting smb file share

diff --git a/bin/backup b/bin/backup
--- a/bin/backup
+++ b/bin/backup
@@ -4,23 +4,39 @@ CONF_DIR="$(dirname $0)/.."
 . "$CONF_DIR/backup.conf"
 
 #temporary, nanti diganti
-BACKUP_SAVE="/mnt/backup_smb/testing_backup"
-
-#dihold dulu
+BACKUP_SAVE=""
 smb_mount ()
 {
-	SMB_OPTIONS=""
+        SMB_OPTIONS=""
         MOUNTED_URL=$(mount | grep "$SMB_URL" | sed -e 's/^.*on //g' -e 's/ type.*$//')
-	if [ "$SMB_USER" == "guest" ]
-	then
-		SMB_OPTIONS="${SMB_OPTIONS}guest"
-	else
-		SMB_OPTIONS="${SMB_OPTIONS}username=\"${SMB_USER}\",password=\"${SMB_PASSWORD}\",domain=\"${SMB_DOMAIN}\""
-	fi
 
+        # if smb isn't mounted yet
+        if [ "$MOUNTED_URL" != "$SMB_MOUNT_DIR" ]
+        then
+                # mounting smb
+                echo "Mounting samba file share to $SMB_MOUNT_DIR"
+                if [ "$SMB_USER" == "guest" ]
+                then
+                        SMB_OPTIONS="${SMB_OPTIONS}guest"
+                else
+                        SMB_OPTIONS="${SMB_OPTIONS}username=${SMB_USER},password=${SMB_PASSWORD},domain=${SMB_DOMAIN}"
+                fi
 
-	echo $SMB_OPTIONS
+                mkdir -p "$SMB_MOUNT_DIR"
+                mount.cifs "$SMB_URL" "$SMB_MOUNT_DIR" -o "$SMB_OPTIONS"
+                if [ "$?" -ne 0 ]
+                then
+                        echo "Could not mount smb" >&2 
+                        exit -1
+                else
+                        MOUNTED_URL="$SMB_MOUNT_DIR"
+                fi
+        else
+                echo "SMB file share is already mounted on $MOUNTED_URL"
+        fi
+        BACKUP_SAVE="${MOUNTED_URL}/${BACKUP_DIR}"
 }
+
 
 FULL_TIMESTAMP=""
 NOW_TIMESTAMP=""
@@ -97,6 +113,14 @@ backup_openfire()
 	"$DUPLICITY" "$OPENFIRE_DIR" "file:///$OPENFIRE_SAVE/openfire"
 }
 
+
+if [ "$URL_TYPE" == "smb" ]
+then
+	smb_mount
+else
+	BACKUP_SAVE="$BACKUP_DIR"
+fi
+echo "Backup will be saved in $BACKUP_SAVE"
 
 generate_timestamp
 FILENAME="$(basename $0)"
